NotificationsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: userId
        KeyType: RANGE
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
    GlobalSecondaryIndexes:
      - IndexName: byUserId
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    Tags:
      - Key: Environment
        Value: ${sls:stage}
      - Key: Name
        Value: notifications-table