RetweetsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: tweetId
        KeyType: RANGE
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: tweetId
        AttributeType: S
    Tags:
      - Key: Environment
        Value: ${sls:stage}
      - Key: Name
        Value: retweets-table