UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: screenName
        AttributeType: S
    GlobalSecondaryIndexes:
      - IndexName: byScreenName
        KeySchema:
          - AttributeName: screenName
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    Tags:
      - Key: Environment
        Value: ${sls:stage}
      - Key: Name
        Value: users-table