WebUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId:  !Ref CognitoUserPool
    ClientName: web
    ExplicitAuthFlows:
      - ALLOW_USER_SRP_AUTH
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
    PreventUserExistenceErrors: ENABLED